name: Format Check
on:
  pull_request:
    branches:
      - '**'
jobs:
  black:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Black
        run: |
          python -m pip install --upgrade pip
          pip install black
      - name: Run Black
        run: |
          black --check --verbose .