name: Lint Check
on:
  pull_request:
    branches:
      - '**'
jobs:
  pylint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint pylint-django Django djangorestframework
      - name: Run Pylint
        run: |
          rating=$(pylint --rcfile=.pylintrc Backend/*.py | grep "rated at" | awk -F' ' '{print $7}' | awk -F'/' '{print $1}')
          if (( $(echo "$rating < 7" | bc -l) )); then exit 1; fi
